### ISSUE TITLE
Tracking Issue: Documentation

### ISSUE THREAD

**Issue by meiji163** [nalexai/hyperlib#16]
This is a tracking issue for improving documentation as hyperlib develops.   
This will be important for getting more people to use hyperbolic ML (esp. examples)

- [ ] Standardize function doc strings
- [ ] Generate docs with [sphinx](https://www.sphinx-doc.org/en/master/)
- [ ] Put up documentation site
- [ ] Examples (expand on point this later)
